Make tab shortcut close showWpm when finish
Manoonchai/learn pull request #12
Opened 2021-11-22 03:16 UTC by ronnapatp

2021-11-22 10:22 UTC, tinvv commented on src/routes/index.svelte
> +      if (showWpm = true){
should it be === instead = ?

2021-11-23 02:28 UTC, ronnapatp commented on src/routes/index.svelte
> +      if (showWpm = true){
OK

2021-11-23 02:28 UTC, ronnapatp commented on src/routes/index.svelte
> +      if (showWpm = true){
OK

2021-11-27 12:39 UTC, narze commented on src/routes/index.svelte
> +        showWpm === false
```suggestion
        showWpm = false
```

2021-11-27 12:40 UTC, narze requested changes
^

2021-11-27 12:40 UTC, narze commented on src/routes/index.svelte
> +        showWpm === false
What does this code do I'm not sure, try to explain it in PR description

2021-11-28 12:39 UTC, ronnapatp commented
Done

2021-12-06 07:41 UTC, narze approved these changes

2021-12-06 07:41 UTC, merged